# Site settings
title: Joshua J Coronado
email: joshua@coronado.io
description: > # this means to ignore newlines until "baseurl:"
  Art + Tech 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "joshua.coronado.io" # the base hostname & protocol for your site
github_username:  joshuajcoronado

# Build settings
markdown: kramdown
