# Site settings
title: Joshua J Coronado
email: joshuajcoronado@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Joshua Coronado.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "portfolio.joshuacoronado.com" # the base hostname & protocol for your site
github_username:  jjcorona

# Build settings
markdown: kramdown
